# Generated by Django 5.2.7 on 2025-10-27 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_series_genre_series_release_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_viewers', to='main.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currently_watching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currently_watching',
                'unique_together': {('user', 'series')},
            },
        ),
    ]
